### ISSUE TITLE
UI remains on screen when taking a photo in 1.20.1

### ISSUE THREAD

**Issue by Its-Just-Luci** [forkiesassds/PhotoMode#13]
Hotbar, health etc remains on screen. This may be due to https://modrinth.com/mod/keep-my-hand being installed? photo attached
![2023-10-28_19 18 28](https://github.com/forkiesassds/PhotoMode/assets/57868183/0951ea9a-adb4-420f-896a-d234f1c5954c)

**Comment by forkiesassds** [comment]
I have pushed a new commit on all branches that should hopefully fix this issue. Try seeing if this issue occurs on the latest commit.
